name: Policy Validation CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod +x opa
        sudo mv opa /usr/local/bin/

    - name: Validate Rego policy
      run: |
        opa check policies/require-label.rego 

    - name: Test Rego policy
      run: |
        opa test policies/require-label.rego policies/require-label_test.rego
