name: Policy Validation CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Validate Rego policy
      run: |
        opa check policies/require-label.rego 

    - name: Test Rego policy
      run: |
        opa test policies/require-label.rego policies/require-label_test.rego

    - name: Validate the helm chart using conftest
      uses: YubicoLabs/action-conftest@v3
      with:
          files: conftest test helmcharts/templates/deployment.yaml --policy policies/
