name: Policy Validation CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Validate Rego policy
      run: |
        opa check policies/require-label.rego 

    - name: Test Rego policy
      run: |
        opa test policies/require-label.rego policies/require-label_test.rego

    - name: Install Conftest
      run: |
        curl -LO https://github.com/open-policy-agent/conftest/releases/download/v0.37.0/conftest-linux-amd64
        chmod +x conftest-linux-amd64
        sudo mv conftest-linux-amd64 /usr/local/bin/conftest

    - name: Run Conftest on Helm Charts
      run: conftest test --trace helmcharts/deployment.yaml --policy policies
