name: Policy Validation CI Chart

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Validate Rego policy
      run: |
        opa check policies/require-label.rego 

    - name: Test Rego policy
      run: |
        opa test policies/require-label.rego policies/require-label_test.rego


    - name: Download and Install Conftest
      run: |
        curl -LO https://github.com/open-policy-agent/conftest/releases/download/v0.56.0/conftest_0.56.0_Linux_x86_64.tar.gz
        tar -xzvf conftest_0.56.0_Linux_x86_64.tar.gz
        sudo mv conftest /usr/local/bin
        conftest --version


    - name: conftest version check
      run: conftest --version
      
    - name: Run Conftest on Helm Charts
      run: conftest test --trace helmcharts/deployment.yaml --policy policies
